# coding: utf-8

"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.credit_notes_api import CreditNotesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCreditNotesApi(unittest.TestCase):
    """CreditNotesApi unit test stubs"""

    def setUp(self):
        self.api = CreditNotesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_companies_company_id_connections_connection_id_push_credit_notes_credit_note_id_put(self):
        """Test case for companies_company_id_connections_connection_id_push_credit_notes_credit_note_id_put

        Posts an updated credit note to the accounting package for a given company.  # noqa: E501
        """
        pass

    def test_companies_company_id_connections_connection_id_push_credit_notes_post(self):
        """Test case for companies_company_id_connections_connection_id_push_credit_notes_post

        """
        pass

    def test_companies_company_id_data_credit_notes_credit_note_id_get(self):
        """Test case for companies_company_id_data_credit_notes_credit_note_id_get

        Gets a single creditNote corresponding to the supplied Id  # noqa: E501
        """
        pass

    def test_companies_company_id_data_credit_notes_get(self):
        """Test case for companies_company_id_data_credit_notes_get

        Gets a list of all credit notes for a company, with pagination  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
