# coding: utf-8

"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.codat_public_api_models_data_cash_flow_statement_response import CodatPublicApiModelsDataCashFlowStatementResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestCodatPublicApiModelsDataCashFlowStatementResponse(unittest.TestCase):
    """CodatPublicApiModelsDataCashFlowStatementResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCodatPublicApiModelsDataCashFlowStatementResponse(self):
        """Test CodatPublicApiModelsDataCashFlowStatementResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.codat_public_api_models_data_cash_flow_statement_response.CodatPublicApiModelsDataCashFlowStatementResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
