"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import codat_python_sdk
from codat_python_sdk.model.codat_public_api_models_metadata_confirmed_account_category_model import CodatPublicApiModelsMetadataConfirmedAccountCategoryModel
from codat_python_sdk.model.codat_public_api_models_metadata_patch_account_ref_model import CodatPublicApiModelsMetadataPatchAccountRefModel
globals()['CodatPublicApiModelsMetadataConfirmedAccountCategoryModel'] = CodatPublicApiModelsMetadataConfirmedAccountCategoryModel
globals()['CodatPublicApiModelsMetadataPatchAccountRefModel'] = CodatPublicApiModelsMetadataPatchAccountRefModel
from codat_python_sdk.model.codat_public_api_models_metadata_patch_account_category_model import CodatPublicApiModelsMetadataPatchAccountCategoryModel


class TestCodatPublicApiModelsMetadataPatchAccountCategoryModel(unittest.TestCase):
    """CodatPublicApiModelsMetadataPatchAccountCategoryModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCodatPublicApiModelsMetadataPatchAccountCategoryModel(self):
        """Test CodatPublicApiModelsMetadataPatchAccountCategoryModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CodatPublicApiModelsMetadataPatchAccountCategoryModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
