# coding: utf-8

"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.codat_clients_api_client_contract_supported_data_path import CodatClientsApiClientContractSupportedDataPath  # noqa: E501
from swagger_client.rest import ApiException


class TestCodatClientsApiClientContractSupportedDataPath(unittest.TestCase):
    """CodatClientsApiClientContractSupportedDataPath unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCodatClientsApiClientContractSupportedDataPath(self):
        """Test CodatClientsApiClientContractSupportedDataPath"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.codat_clients_api_client_contract_supported_data_path.CodatClientsApiClientContractSupportedDataPath()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
