"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import codat_python_sdk
from codat_python_sdk.api.commerce_info_api import CommerceInfoApi  # noqa: E501


class TestCommerceInfoApi(unittest.TestCase):
    """CommerceInfoApi unit test stubs"""

    def setUp(self):
        self.api = CommerceInfoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_companies_company_id_connections_connection_id_data_commerce_info_get(self):
        """Test case for companies_company_id_connections_connection_id_data_commerce_info_get

        Gets the latest basic info for a commerce company.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
