"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import codat_python_sdk
from codat_python_sdk.model.system_object_push_operation import SystemObjectPushOperation
from codat_python_sdk.model.system_object_push_operation_paged_response_links_model import SystemObjectPushOperationPagedResponseLinksModel
globals()['SystemObjectPushOperation'] = SystemObjectPushOperation
globals()['SystemObjectPushOperationPagedResponseLinksModel'] = SystemObjectPushOperationPagedResponseLinksModel
from codat_python_sdk.model.system_object_push_operation_paged_response_model import SystemObjectPushOperationPagedResponseModel


class TestSystemObjectPushOperationPagedResponseModel(unittest.TestCase):
    """SystemObjectPushOperationPagedResponseModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSystemObjectPushOperationPagedResponseModel(self):
        """Test SystemObjectPushOperationPagedResponseModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SystemObjectPushOperationPagedResponseModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
