"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import codat_python_sdk
from codat_python_sdk.model.codat_public_api_models_data_dataset_status import CodatPublicApiModelsDataDatasetStatus
globals()['CodatPublicApiModelsDataDatasetStatus'] = CodatPublicApiModelsDataDatasetStatus
from codat_python_sdk.model.codat_public_api_models_data_data_set import CodatPublicApiModelsDataDataSet


class TestCodatPublicApiModelsDataDataSet(unittest.TestCase):
    """CodatPublicApiModelsDataDataSet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCodatPublicApiModelsDataDataSet(self):
        """Test CodatPublicApiModelsDataDataSet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CodatPublicApiModelsDataDataSet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
