"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import codat_python_sdk
from codat_python_sdk.api.connection_api import ConnectionApi  # noqa: E501


class TestConnectionApi(unittest.TestCase):
    """ConnectionApi unit test stubs"""

    def setUp(self):
        self.api = ConnectionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_companies_company_id_connections_connection_id_delete(self):
        """Test case for companies_company_id_connections_connection_id_delete

        Disconnect and delete a data source from a company  # noqa: E501
        """
        pass

    def test_companies_company_id_connections_connection_id_get(self):
        """Test case for companies_company_id_connections_connection_id_get

        Retrieve a single data source connected to a single company, including its connection status  # noqa: E501
        """
        pass

    def test_companies_company_id_connections_connection_id_patch(self):
        """Test case for companies_company_id_connections_connection_id_patch

        Disconnect a data source from a company  # noqa: E501
        """
        pass

    def test_companies_company_id_connections_get(self):
        """Test case for companies_company_id_connections_get

        Retrieve all data sources connected to a single company, including their connection statuses  # noqa: E501
        """
        pass

    def test_companies_company_id_connections_post(self):
        """Test case for companies_company_id_connections_post

        Connect a data source to a company  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
