"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import codat_python_sdk
from codat_python_sdk.model.codat_public_api_models_company_patch_data_connection_model import CodatPublicApiModelsCompanyPatchDataConnectionModel


class TestCodatPublicApiModelsCompanyPatchDataConnectionModel(unittest.TestCase):
    """CodatPublicApiModelsCompanyPatchDataConnectionModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCodatPublicApiModelsCompanyPatchDataConnectionModel(self):
        """Test CodatPublicApiModelsCompanyPatchDataConnectionModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CodatPublicApiModelsCompanyPatchDataConnectionModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
