"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import codat_python_sdk
from codat_python_sdk.model.codat_public_api_models_rules_notifiers import CodatPublicApiModelsRulesNotifiers
globals()['CodatPublicApiModelsRulesNotifiers'] = CodatPublicApiModelsRulesNotifiers
from codat_python_sdk.model.codat_public_api_models_rules_rule import CodatPublicApiModelsRulesRule


class TestCodatPublicApiModelsRulesRule(unittest.TestCase):
    """CodatPublicApiModelsRulesRule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCodatPublicApiModelsRulesRule(self):
        """Test CodatPublicApiModelsRulesRule"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CodatPublicApiModelsRulesRule()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
