# coding: utf-8

"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.rules_api import RulesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRulesApi(unittest.TestCase):
    """RulesApi unit test stubs"""

    def setUp(self):
        self.api = RulesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_rules_alerts_alert_id_get(self):
        """Test case for rules_alerts_alert_id_get

        """
        pass

    def test_rules_alerts_alert_id_resolve_post(self):
        """Test case for rules_alerts_alert_id_resolve_post

        """
        pass

    def test_rules_alerts_get(self):
        """Test case for rules_alerts_get

        """
        pass

    def test_rules_get(self):
        """Test case for rules_get

        Fetch a list of rules a company is subscribed to  # noqa: E501
        """
        pass

    def test_rules_post(self):
        """Test case for rules_post

        Subscribe to a rule  # noqa: E501
        """
        pass

    def test_rules_rule_id_alerts_get(self):
        """Test case for rules_rule_id_alerts_get

        """
        pass

    def test_rules_rule_id_delete(self):
        """Test case for rules_rule_id_delete

        """
        pass

    def test_rules_rule_id_get(self):
        """Test case for rules_rule_id_get

        """
        pass

    def test_rules_rule_id_put(self):
        """Test case for rules_rule_id_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
