"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import codat_python_sdk
from codat_python_sdk.model.codat_data_contracts_push_option_type import CodatDataContractsPushOptionType


class TestCodatDataContractsPushOptionType(unittest.TestCase):
    """CodatDataContractsPushOptionType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCodatDataContractsPushOptionType(self):
        """Test CodatDataContractsPushOptionType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CodatDataContractsPushOptionType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
