"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import codat_python_sdk
from codat_python_sdk.api.journals_api import JournalsApi  # noqa: E501


class TestJournalsApi(unittest.TestCase):
    """JournalsApi unit test stubs"""

    def setUp(self):
        self.api = JournalsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_companies_company_id_connections_connection_id_push_journal_entries_post(self):
        """Test case for companies_company_id_connections_connection_id_push_journal_entries_post

        Posts a new journalEntry to the accounting package for a given company.  # noqa: E501
        """
        pass

    def test_companies_company_id_data_journal_entries_get(self):
        """Test case for companies_company_id_data_journal_entries_get

        Gets the latest journal entries for a company, with pagination  # noqa: E501
        """
        pass

    def test_companies_company_id_data_journal_entries_journal_entry_id_get(self):
        """Test case for companies_company_id_data_journal_entries_journal_entry_id_get

        Gets a single JournalEntry corresponding to the supplied Id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
