"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import codat_python_sdk
from codat_python_sdk.model.codat_public_api_models_clients_client_settings_model import CodatPublicApiModelsClientsClientSettingsModel


class TestCodatPublicApiModelsClientsClientSettingsModel(unittest.TestCase):
    """CodatPublicApiModelsClientsClientSettingsModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCodatPublicApiModelsClientsClientSettingsModel(self):
        """Test CodatPublicApiModelsClientsClientSettingsModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CodatPublicApiModelsClientsClientSettingsModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
