# coding: utf-8

"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import codat_python_sdk
from codat_python_sdk.models.codat_rules_contracts_responses_alert_paged_response_links_model import CodatRulesContractsResponsesAlertPagedResponseLinksModel  # noqa: E501
from codat_python_sdk.rest import ApiException


class TestCodatRulesContractsResponsesAlertPagedResponseLinksModel(unittest.TestCase):
    """CodatRulesContractsResponsesAlertPagedResponseLinksModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCodatRulesContractsResponsesAlertPagedResponseLinksModel(self):
        """Test CodatRulesContractsResponsesAlertPagedResponseLinksModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = codat_python_sdk.models.codat_rules_contracts_responses_alert_paged_response_links_model.CodatRulesContractsResponsesAlertPagedResponseLinksModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
