# coding: utf-8

"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import codat_python_sdk
from codat_python_sdk.models.codat_public_api_models_clients_integration_settings_model import CodatPublicApiModelsClientsIntegrationSettingsModel  # noqa: E501
from codat_python_sdk.rest import ApiException


class TestCodatPublicApiModelsClientsIntegrationSettingsModel(unittest.TestCase):
    """CodatPublicApiModelsClientsIntegrationSettingsModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCodatPublicApiModelsClientsIntegrationSettingsModel(self):
        """Test CodatPublicApiModelsClientsIntegrationSettingsModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = codat_python_sdk.models.codat_public_api_models_clients_integration_settings_model.CodatPublicApiModelsClientsIntegrationSettingsModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
