"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import codat_python_sdk
from codat_python_sdk.model.codat_public_api_models_platform_credentials_platform_source_model import CodatPublicApiModelsPlatformCredentialsPlatformSourceModel
from codat_python_sdk.model.codat_public_api_models_platform_credentials_platform_source_model_paged_response_links_model import CodatPublicApiModelsPlatformCredentialsPlatformSourceModelPagedResponseLinksModel
globals()['CodatPublicApiModelsPlatformCredentialsPlatformSourceModel'] = CodatPublicApiModelsPlatformCredentialsPlatformSourceModel
globals()['CodatPublicApiModelsPlatformCredentialsPlatformSourceModelPagedResponseLinksModel'] = CodatPublicApiModelsPlatformCredentialsPlatformSourceModelPagedResponseLinksModel
from codat_python_sdk.model.codat_public_api_models_platform_credentials_platform_source_model_paged_response_model import CodatPublicApiModelsPlatformCredentialsPlatformSourceModelPagedResponseModel


class TestCodatPublicApiModelsPlatformCredentialsPlatformSourceModelPagedResponseModel(unittest.TestCase):
    """CodatPublicApiModelsPlatformCredentialsPlatformSourceModelPagedResponseModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCodatPublicApiModelsPlatformCredentialsPlatformSourceModelPagedResponseModel(self):
        """Test CodatPublicApiModelsPlatformCredentialsPlatformSourceModelPagedResponseModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CodatPublicApiModelsPlatformCredentialsPlatformSourceModelPagedResponseModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
