# coding: utf-8

"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.codat_rules_contracts_responses_alert_paged_response_model import CodatRulesContractsResponsesAlertPagedResponseModel  # noqa: E501
from swagger_client.rest import ApiException


class TestCodatRulesContractsResponsesAlertPagedResponseModel(unittest.TestCase):
    """CodatRulesContractsResponsesAlertPagedResponseModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCodatRulesContractsResponsesAlertPagedResponseModel(self):
        """Test CodatRulesContractsResponsesAlertPagedResponseModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.codat_rules_contracts_responses_alert_paged_response_model.CodatRulesContractsResponsesAlertPagedResponseModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
