# coding: utf-8

"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import codat_python_sdk
from codat_python_sdk.api.push_api import PushApi  # noqa: E501
from codat_python_sdk.rest import ApiException


class TestPushApi(unittest.TestCase):
    """PushApi unit test stubs"""

    def setUp(self):
        self.api = PushApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_companies_company_id_connections_connection_id_options_data_type_get(self):
        """Test case for companies_company_id_connections_connection_id_options_data_type_get

        Gets the push options for the given data type  # noqa: E501
        """
        pass

    def test_companies_company_id_push_get(self):
        """Test case for companies_company_id_push_get

        Gets paged push operation records  # noqa: E501
        """
        pass

    def test_companies_company_id_push_push_operation_key_get(self):
        """Test case for companies_company_id_push_push_operation_key_get

        Gets a single push operation record  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
