"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import codat_python_sdk
from codat_python_sdk.model.codat_public_api_models_data_valid_datatype_links_response import CodatPublicApiModelsDataValidDatatypeLinksResponse


class TestCodatPublicApiModelsDataValidDatatypeLinksResponse(unittest.TestCase):
    """CodatPublicApiModelsDataValidDatatypeLinksResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCodatPublicApiModelsDataValidDatatypeLinksResponse(self):
        """Test CodatPublicApiModelsDataValidDatatypeLinksResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CodatPublicApiModelsDataValidDatatypeLinksResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
