# coding: utf-8

"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import codat_python_sdk
from codat_python_sdk.api.bill_payments_api import BillPaymentsApi  # noqa: E501
from codat_python_sdk.rest import ApiException


class TestBillPaymentsApi(unittest.TestCase):
    """BillPaymentsApi unit test stubs"""

    def setUp(self):
        self.api = BillPaymentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_companies_company_id_connections_connection_id_push_bill_payments_post(self):
        """Test case for companies_company_id_connections_connection_id_push_bill_payments_post

        Posts a new bill payment to the accounting package for a given company.  # noqa: E501
        """
        pass

    def test_companies_company_id_data_bill_payments_bill_payment_id_get(self):
        """Test case for companies_company_id_data_bill_payments_bill_payment_id_get

        """
        pass

    def test_companies_company_id_data_bill_payments_get(self):
        """Test case for companies_company_id_data_bill_payments_get

        Gets the latest billPayments for a company, with pagination  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
