"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import codat_python_sdk
from codat_python_sdk.model.codat_data_contracts_datasets_balance_sheet import CodatDataContractsDatasetsBalanceSheet
globals()['CodatDataContractsDatasetsBalanceSheet'] = CodatDataContractsDatasetsBalanceSheet
from codat_python_sdk.model.codat_public_api_models_data_balance_sheet_response import CodatPublicApiModelsDataBalanceSheetResponse


class TestCodatPublicApiModelsDataBalanceSheetResponse(unittest.TestCase):
    """CodatPublicApiModelsDataBalanceSheetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCodatPublicApiModelsDataBalanceSheetResponse(self):
        """Test CodatPublicApiModelsDataBalanceSheetResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CodatPublicApiModelsDataBalanceSheetResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
