"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import codat_python_sdk
from codat_python_sdk.api.commerce_transactions_api import CommerceTransactionsApi  # noqa: E501


class TestCommerceTransactionsApi(unittest.TestCase):
    """CommerceTransactionsApi unit test stubs"""

    def setUp(self):
        self.api = CommerceTransactionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_companies_company_id_connections_connection_id_data_commerce_transactions_get(self):
        """Test case for companies_company_id_connections_connection_id_data_commerce_transactions_get

        Gets the latest commerce transactions for a company, with pagination  # noqa: E501
        """
        pass

    def test_companies_company_id_connections_connection_id_data_commerce_transactions_transaction_id_get(self):
        """Test case for companies_company_id_connections_connection_id_data_commerce_transactions_transaction_id_get

        Gets the specified commerce transaction for a given company  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
