"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import codat_python_sdk
from codat_python_sdk.model.codat_public_api_models_company_data_connection import CodatPublicApiModelsCompanyDataConnection
from codat_python_sdk.model.codat_public_api_models_company_data_connection_paged_response_links_model import CodatPublicApiModelsCompanyDataConnectionPagedResponseLinksModel
globals()['CodatPublicApiModelsCompanyDataConnection'] = CodatPublicApiModelsCompanyDataConnection
globals()['CodatPublicApiModelsCompanyDataConnectionPagedResponseLinksModel'] = CodatPublicApiModelsCompanyDataConnectionPagedResponseLinksModel
from codat_python_sdk.model.codat_public_api_models_company_data_connection_paged_response_model import CodatPublicApiModelsCompanyDataConnectionPagedResponseModel


class TestCodatPublicApiModelsCompanyDataConnectionPagedResponseModel(unittest.TestCase):
    """CodatPublicApiModelsCompanyDataConnectionPagedResponseModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCodatPublicApiModelsCompanyDataConnectionPagedResponseModel(self):
        """Test CodatPublicApiModelsCompanyDataConnectionPagedResponseModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CodatPublicApiModelsCompanyDataConnectionPagedResponseModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
