"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import codat_python_sdk
from codat_python_sdk.api.payment_methods_api import PaymentMethodsApi  # noqa: E501


class TestPaymentMethodsApi(unittest.TestCase):
    """PaymentMethodsApi unit test stubs"""

    def setUp(self):
        self.api = PaymentMethodsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_companies_company_id_data_payment_methods_get(self):
        """Test case for companies_company_id_data_payment_methods_get

        Gets the payment methods for a given company.  # noqa: E501
        """
        pass

    def test_companies_company_id_data_payment_methods_payment_method_id_get(self):
        """Test case for companies_company_id_data_payment_methods_payment_method_id_get

        Gets the specified payment method for a given company.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
