# coding: utf-8

"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.companies_api import CompaniesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCompaniesApi(unittest.TestCase):
    """CompaniesApi unit test stubs"""

    def setUp(self):
        self.api = CompaniesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_companies_company_id_delete(self):
        """Test case for companies_company_id_delete

        Deletes a company, this is not reversible.  # noqa: E501
        """
        pass

    def test_companies_company_id_get(self):
        """Test case for companies_company_id_get

        Fetch metadata on a single company.  # noqa: E501
        """
        pass

    def test_companies_company_id_put(self):
        """Test case for companies_company_id_put

        Update a company with a new name  # noqa: E501
        """
        pass

    def test_companies_company_id_settings_get(self):
        """Test case for companies_company_id_settings_get

        Fetch settings on a single company.  # noqa: E501
        """
        pass

    def test_companies_company_id_settings_put(self):
        """Test case for companies_company_id_settings_put

        Update settings on a single company.  # noqa: E501
        """
        pass

    def test_companies_company_id_sync_settings_get(self):
        """Test case for companies_company_id_sync_settings_get

        """
        pass

    def test_companies_company_id_sync_settings_post(self):
        """Test case for companies_company_id_sync_settings_post

        """
        pass

    def test_companies_get(self):
        """Test case for companies_get

        Fetch a list of all companies metadata with accounting links on the Codat platform  # noqa: E501
        """
        pass

    def test_companies_post(self):
        """Test case for companies_post

        Initiate the process of onboarding a new company on the Codat platform  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
