"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import codat_python_sdk
from codat_python_sdk.model.codat_clients_api_client_contract_company_settings import CodatClientsApiClientContractCompanySettings


class TestCodatClientsApiClientContractCompanySettings(unittest.TestCase):
    """CodatClientsApiClientContractCompanySettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCodatClientsApiClientContractCompanySettings(self):
        """Test CodatClientsApiClientContractCompanySettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CodatClientsApiClientContractCompanySettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
