"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import codat_python_sdk
from codat_python_sdk.api.tracking_categories_api import TrackingCategoriesApi  # noqa: E501


class TestTrackingCategoriesApi(unittest.TestCase):
    """TrackingCategoriesApi unit test stubs"""

    def setUp(self):
        self.api = TrackingCategoriesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_companies_company_id_data_tracking_categories_get(self):
        """Test case for companies_company_id_data_tracking_categories_get

        Gets the latest tracking categories for a given company.  # noqa: E501
        """
        pass

    def test_companies_company_id_data_tracking_categories_tracking_category_id_get(self):
        """Test case for companies_company_id_data_tracking_categories_tracking_category_id_get

        Gets the specified tracking categories for a given company.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
