# coding: utf-8

"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.codat_data_contracts_push_push_field_validation import CodatDataContractsPushPushFieldValidation  # noqa: E501
from swagger_client.rest import ApiException


class TestCodatDataContractsPushPushFieldValidation(unittest.TestCase):
    """CodatDataContractsPushPushFieldValidation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCodatDataContractsPushPushFieldValidation(self):
        """Test CodatDataContractsPushPushFieldValidation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.codat_data_contracts_push_push_field_validation.CodatDataContractsPushPushFieldValidation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
