"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import codat_python_sdk
from codat_python_sdk.model.codat_public_api_models_metadata_account_categories_model import CodatPublicApiModelsMetadataAccountCategoriesModel
from codat_python_sdk.model.codat_public_api_models_metadata_account_categories_model_paged_response_links_model import CodatPublicApiModelsMetadataAccountCategoriesModelPagedResponseLinksModel
globals()['CodatPublicApiModelsMetadataAccountCategoriesModel'] = CodatPublicApiModelsMetadataAccountCategoriesModel
globals()['CodatPublicApiModelsMetadataAccountCategoriesModelPagedResponseLinksModel'] = CodatPublicApiModelsMetadataAccountCategoriesModelPagedResponseLinksModel
from codat_python_sdk.model.codat_public_api_models_metadata_account_categories_model_paged_response_model import CodatPublicApiModelsMetadataAccountCategoriesModelPagedResponseModel


class TestCodatPublicApiModelsMetadataAccountCategoriesModelPagedResponseModel(unittest.TestCase):
    """CodatPublicApiModelsMetadataAccountCategoriesModelPagedResponseModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCodatPublicApiModelsMetadataAccountCategoriesModelPagedResponseModel(self):
        """Test CodatPublicApiModelsMetadataAccountCategoriesModelPagedResponseModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CodatPublicApiModelsMetadataAccountCategoriesModelPagedResponseModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
