"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import codat_python_sdk
from codat_python_sdk.model.codat_public_api_models_metadata_patch_account_category_model import CodatPublicApiModelsMetadataPatchAccountCategoryModel
globals()['CodatPublicApiModelsMetadataPatchAccountCategoryModel'] = CodatPublicApiModelsMetadataPatchAccountCategoryModel
from codat_python_sdk.model.codat_public_api_models_metadata_patch_account_categories_model import CodatPublicApiModelsMetadataPatchAccountCategoriesModel


class TestCodatPublicApiModelsMetadataPatchAccountCategoriesModel(unittest.TestCase):
    """CodatPublicApiModelsMetadataPatchAccountCategoriesModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCodatPublicApiModelsMetadataPatchAccountCategoriesModel(self):
        """Test CodatPublicApiModelsMetadataPatchAccountCategoriesModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CodatPublicApiModelsMetadataPatchAccountCategoriesModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
