"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import codat_python_sdk
from codat_python_sdk.api.profile_api import ProfileApi  # noqa: E501


class TestProfileApi(unittest.TestCase):
    """ProfileApi unit test stubs"""

    def setUp(self):
        self.api = ProfileApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_profile_api_key_put(self):
        """Test case for profile_api_key_put

        Refresh the existing API key for your clients.  # noqa: E501
        """
        pass

    def test_profile_get(self):
        """Test case for profile_get

        Fetch your organisations company profile  # noqa: E501
        """
        pass

    def test_profile_put(self):
        """Test case for profile_put

        Update your organisations company profile  # noqa: E501
        """
        pass

    def test_profile_sync_settings_get(self):
        """Test case for profile_sync_settings_get

        """
        pass

    def test_profile_sync_settings_post(self):
        """Test case for profile_sync_settings_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
