# coding: utf-8

"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CodatPublicApiModelsClientsIntegrationSettingsModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'integration_id': 'str',
        'one_time_sync': 'str'
    }

    attribute_map = {
        'integration_id': 'integrationId',
        'one_time_sync': 'oneTimeSync'
    }

    def __init__(self, integration_id=None, one_time_sync=None):  # noqa: E501
        """CodatPublicApiModelsClientsIntegrationSettingsModel - a model defined in Swagger"""  # noqa: E501
        self._integration_id = None
        self._one_time_sync = None
        self.discriminator = None
        if integration_id is not None:
            self.integration_id = integration_id
        if one_time_sync is not None:
            self.one_time_sync = one_time_sync

    @property
    def integration_id(self):
        """Gets the integration_id of this CodatPublicApiModelsClientsIntegrationSettingsModel.  # noqa: E501


        :return: The integration_id of this CodatPublicApiModelsClientsIntegrationSettingsModel.  # noqa: E501
        :rtype: str
        """
        return self._integration_id

    @integration_id.setter
    def integration_id(self, integration_id):
        """Sets the integration_id of this CodatPublicApiModelsClientsIntegrationSettingsModel.


        :param integration_id: The integration_id of this CodatPublicApiModelsClientsIntegrationSettingsModel.  # noqa: E501
        :type: str
        """

        self._integration_id = integration_id

    @property
    def one_time_sync(self):
        """Gets the one_time_sync of this CodatPublicApiModelsClientsIntegrationSettingsModel.  # noqa: E501


        :return: The one_time_sync of this CodatPublicApiModelsClientsIntegrationSettingsModel.  # noqa: E501
        :rtype: str
        """
        return self._one_time_sync

    @one_time_sync.setter
    def one_time_sync(self, one_time_sync):
        """Sets the one_time_sync of this CodatPublicApiModelsClientsIntegrationSettingsModel.


        :param one_time_sync: The one_time_sync of this CodatPublicApiModelsClientsIntegrationSettingsModel.  # noqa: E501
        :type: str
        """

        self._one_time_sync = one_time_sync

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CodatPublicApiModelsClientsIntegrationSettingsModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CodatPublicApiModelsClientsIntegrationSettingsModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
