# coding: utf-8

"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CodatPublicApiModelsMetadataValidCategoryType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'subtype': 'str',
        'subtype_display_name': 'str',
        'detail_type': 'str',
        'detail_type_display_name': 'str',
        'detail_type_description': 'str'
    }

    attribute_map = {
        'type': 'type',
        'subtype': 'subtype',
        'subtype_display_name': 'subtypeDisplayName',
        'detail_type': 'detailType',
        'detail_type_display_name': 'detailTypeDisplayName',
        'detail_type_description': 'detailTypeDescription'
    }

    def __init__(self, type=None, subtype=None, subtype_display_name=None, detail_type=None, detail_type_display_name=None, detail_type_description=None):  # noqa: E501
        """CodatPublicApiModelsMetadataValidCategoryType - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._subtype = None
        self._subtype_display_name = None
        self._detail_type = None
        self._detail_type_display_name = None
        self._detail_type_description = None
        self.discriminator = None
        if type is not None:
            self.type = type
        if subtype is not None:
            self.subtype = subtype
        if subtype_display_name is not None:
            self.subtype_display_name = subtype_display_name
        if detail_type is not None:
            self.detail_type = detail_type
        if detail_type_display_name is not None:
            self.detail_type_display_name = detail_type_display_name
        if detail_type_description is not None:
            self.detail_type_description = detail_type_description

    @property
    def type(self):
        """Gets the type of this CodatPublicApiModelsMetadataValidCategoryType.  # noqa: E501


        :return: The type of this CodatPublicApiModelsMetadataValidCategoryType.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this CodatPublicApiModelsMetadataValidCategoryType.


        :param type: The type of this CodatPublicApiModelsMetadataValidCategoryType.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def subtype(self):
        """Gets the subtype of this CodatPublicApiModelsMetadataValidCategoryType.  # noqa: E501


        :return: The subtype of this CodatPublicApiModelsMetadataValidCategoryType.  # noqa: E501
        :rtype: str
        """
        return self._subtype

    @subtype.setter
    def subtype(self, subtype):
        """Sets the subtype of this CodatPublicApiModelsMetadataValidCategoryType.


        :param subtype: The subtype of this CodatPublicApiModelsMetadataValidCategoryType.  # noqa: E501
        :type: str
        """

        self._subtype = subtype

    @property
    def subtype_display_name(self):
        """Gets the subtype_display_name of this CodatPublicApiModelsMetadataValidCategoryType.  # noqa: E501


        :return: The subtype_display_name of this CodatPublicApiModelsMetadataValidCategoryType.  # noqa: E501
        :rtype: str
        """
        return self._subtype_display_name

    @subtype_display_name.setter
    def subtype_display_name(self, subtype_display_name):
        """Sets the subtype_display_name of this CodatPublicApiModelsMetadataValidCategoryType.


        :param subtype_display_name: The subtype_display_name of this CodatPublicApiModelsMetadataValidCategoryType.  # noqa: E501
        :type: str
        """

        self._subtype_display_name = subtype_display_name

    @property
    def detail_type(self):
        """Gets the detail_type of this CodatPublicApiModelsMetadataValidCategoryType.  # noqa: E501


        :return: The detail_type of this CodatPublicApiModelsMetadataValidCategoryType.  # noqa: E501
        :rtype: str
        """
        return self._detail_type

    @detail_type.setter
    def detail_type(self, detail_type):
        """Sets the detail_type of this CodatPublicApiModelsMetadataValidCategoryType.


        :param detail_type: The detail_type of this CodatPublicApiModelsMetadataValidCategoryType.  # noqa: E501
        :type: str
        """

        self._detail_type = detail_type

    @property
    def detail_type_display_name(self):
        """Gets the detail_type_display_name of this CodatPublicApiModelsMetadataValidCategoryType.  # noqa: E501


        :return: The detail_type_display_name of this CodatPublicApiModelsMetadataValidCategoryType.  # noqa: E501
        :rtype: str
        """
        return self._detail_type_display_name

    @detail_type_display_name.setter
    def detail_type_display_name(self, detail_type_display_name):
        """Sets the detail_type_display_name of this CodatPublicApiModelsMetadataValidCategoryType.


        :param detail_type_display_name: The detail_type_display_name of this CodatPublicApiModelsMetadataValidCategoryType.  # noqa: E501
        :type: str
        """

        self._detail_type_display_name = detail_type_display_name

    @property
    def detail_type_description(self):
        """Gets the detail_type_description of this CodatPublicApiModelsMetadataValidCategoryType.  # noqa: E501


        :return: The detail_type_description of this CodatPublicApiModelsMetadataValidCategoryType.  # noqa: E501
        :rtype: str
        """
        return self._detail_type_description

    @detail_type_description.setter
    def detail_type_description(self, detail_type_description):
        """Sets the detail_type_description of this CodatPublicApiModelsMetadataValidCategoryType.


        :param detail_type_description: The detail_type_description of this CodatPublicApiModelsMetadataValidCategoryType.  # noqa: E501
        :type: str
        """

        self._detail_type_description = detail_type_description

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CodatPublicApiModelsMetadataValidCategoryType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CodatPublicApiModelsMetadataValidCategoryType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
