# coding: utf-8

"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CodatPublicApiModelsRulesNotifiers(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'emails': 'list[str]',
        'webhook': 'str'
    }

    attribute_map = {
        'emails': 'emails',
        'webhook': 'webhook'
    }

    def __init__(self, emails=None, webhook=None):  # noqa: E501
        """CodatPublicApiModelsRulesNotifiers - a model defined in Swagger"""  # noqa: E501
        self._emails = None
        self._webhook = None
        self.discriminator = None
        if emails is not None:
            self.emails = emails
        if webhook is not None:
            self.webhook = webhook

    @property
    def emails(self):
        """Gets the emails of this CodatPublicApiModelsRulesNotifiers.  # noqa: E501


        :return: The emails of this CodatPublicApiModelsRulesNotifiers.  # noqa: E501
        :rtype: list[str]
        """
        return self._emails

    @emails.setter
    def emails(self, emails):
        """Sets the emails of this CodatPublicApiModelsRulesNotifiers.


        :param emails: The emails of this CodatPublicApiModelsRulesNotifiers.  # noqa: E501
        :type: list[str]
        """

        self._emails = emails

    @property
    def webhook(self):
        """Gets the webhook of this CodatPublicApiModelsRulesNotifiers.  # noqa: E501


        :return: The webhook of this CodatPublicApiModelsRulesNotifiers.  # noqa: E501
        :rtype: str
        """
        return self._webhook

    @webhook.setter
    def webhook(self, webhook):
        """Sets the webhook of this CodatPublicApiModelsRulesNotifiers.


        :param webhook: The webhook of this CodatPublicApiModelsRulesNotifiers.  # noqa: E501
        :type: str
        """

        self._webhook = webhook

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CodatPublicApiModelsRulesNotifiers, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CodatPublicApiModelsRulesNotifiers):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
