# coding: utf-8

"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CodatPublicApiModelsCompanyCompanyEventStreamItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'description': 'str',
        'event_time_utc': 'datetime'
    }

    attribute_map = {
        'type': 'type',
        'description': 'description',
        'event_time_utc': 'eventTimeUtc'
    }

    def __init__(self, type=None, description=None, event_time_utc=None):  # noqa: E501
        """CodatPublicApiModelsCompanyCompanyEventStreamItem - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._description = None
        self._event_time_utc = None
        self.discriminator = None
        self.type = type
        self.description = description
        self.event_time_utc = event_time_utc

    @property
    def type(self):
        """Gets the type of this CodatPublicApiModelsCompanyCompanyEventStreamItem.  # noqa: E501


        :return: The type of this CodatPublicApiModelsCompanyCompanyEventStreamItem.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this CodatPublicApiModelsCompanyCompanyEventStreamItem.


        :param type: The type of this CodatPublicApiModelsCompanyCompanyEventStreamItem.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def description(self):
        """Gets the description of this CodatPublicApiModelsCompanyCompanyEventStreamItem.  # noqa: E501


        :return: The description of this CodatPublicApiModelsCompanyCompanyEventStreamItem.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CodatPublicApiModelsCompanyCompanyEventStreamItem.


        :param description: The description of this CodatPublicApiModelsCompanyCompanyEventStreamItem.  # noqa: E501
        :type: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def event_time_utc(self):
        """Gets the event_time_utc of this CodatPublicApiModelsCompanyCompanyEventStreamItem.  # noqa: E501


        :return: The event_time_utc of this CodatPublicApiModelsCompanyCompanyEventStreamItem.  # noqa: E501
        :rtype: datetime
        """
        return self._event_time_utc

    @event_time_utc.setter
    def event_time_utc(self, event_time_utc):
        """Sets the event_time_utc of this CodatPublicApiModelsCompanyCompanyEventStreamItem.


        :param event_time_utc: The event_time_utc of this CodatPublicApiModelsCompanyCompanyEventStreamItem.  # noqa: E501
        :type: datetime
        """
        if event_time_utc is None:
            raise ValueError("Invalid value for `event_time_utc`, must not be `None`")  # noqa: E501

        self._event_time_utc = event_time_utc

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CodatPublicApiModelsCompanyCompanyEventStreamItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CodatPublicApiModelsCompanyCompanyEventStreamItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
