# coding: utf-8

"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CodatPublicApiModelsClientsIntegrationBrandingModelLogoModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'full': 'CodatPublicApiModelsClientsIntegrationBrandingModelFullModel',
        'square': 'CodatPublicApiModelsClientsIntegrationBrandingModelSquareModel'
    }

    attribute_map = {
        'full': 'full',
        'square': 'square'
    }

    def __init__(self, full=None, square=None):  # noqa: E501
        """CodatPublicApiModelsClientsIntegrationBrandingModelLogoModel - a model defined in Swagger"""  # noqa: E501
        self._full = None
        self._square = None
        self.discriminator = None
        if full is not None:
            self.full = full
        if square is not None:
            self.square = square

    @property
    def full(self):
        """Gets the full of this CodatPublicApiModelsClientsIntegrationBrandingModelLogoModel.  # noqa: E501


        :return: The full of this CodatPublicApiModelsClientsIntegrationBrandingModelLogoModel.  # noqa: E501
        :rtype: CodatPublicApiModelsClientsIntegrationBrandingModelFullModel
        """
        return self._full

    @full.setter
    def full(self, full):
        """Sets the full of this CodatPublicApiModelsClientsIntegrationBrandingModelLogoModel.


        :param full: The full of this CodatPublicApiModelsClientsIntegrationBrandingModelLogoModel.  # noqa: E501
        :type: CodatPublicApiModelsClientsIntegrationBrandingModelFullModel
        """

        self._full = full

    @property
    def square(self):
        """Gets the square of this CodatPublicApiModelsClientsIntegrationBrandingModelLogoModel.  # noqa: E501


        :return: The square of this CodatPublicApiModelsClientsIntegrationBrandingModelLogoModel.  # noqa: E501
        :rtype: CodatPublicApiModelsClientsIntegrationBrandingModelSquareModel
        """
        return self._square

    @square.setter
    def square(self, square):
        """Sets the square of this CodatPublicApiModelsClientsIntegrationBrandingModelLogoModel.


        :param square: The square of this CodatPublicApiModelsClientsIntegrationBrandingModelLogoModel.  # noqa: E501
        :type: CodatPublicApiModelsClientsIntegrationBrandingModelSquareModel
        """

        self._square = square

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CodatPublicApiModelsClientsIntegrationBrandingModelLogoModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CodatPublicApiModelsClientsIntegrationBrandingModelLogoModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
