# coding: utf-8

"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CodatDataContractsValidationValidationItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'item_id': 'str',
        'message': 'str',
        'validator_name': 'str'
    }

    attribute_map = {
        'item_id': 'itemId',
        'message': 'message',
        'validator_name': 'validatorName'
    }

    def __init__(self, item_id=None, message=None, validator_name=None):  # noqa: E501
        """CodatDataContractsValidationValidationItem - a model defined in Swagger"""  # noqa: E501
        self._item_id = None
        self._message = None
        self._validator_name = None
        self.discriminator = None
        if item_id is not None:
            self.item_id = item_id
        if message is not None:
            self.message = message
        if validator_name is not None:
            self.validator_name = validator_name

    @property
    def item_id(self):
        """Gets the item_id of this CodatDataContractsValidationValidationItem.  # noqa: E501


        :return: The item_id of this CodatDataContractsValidationValidationItem.  # noqa: E501
        :rtype: str
        """
        return self._item_id

    @item_id.setter
    def item_id(self, item_id):
        """Sets the item_id of this CodatDataContractsValidationValidationItem.


        :param item_id: The item_id of this CodatDataContractsValidationValidationItem.  # noqa: E501
        :type: str
        """

        self._item_id = item_id

    @property
    def message(self):
        """Gets the message of this CodatDataContractsValidationValidationItem.  # noqa: E501


        :return: The message of this CodatDataContractsValidationValidationItem.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this CodatDataContractsValidationValidationItem.


        :param message: The message of this CodatDataContractsValidationValidationItem.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def validator_name(self):
        """Gets the validator_name of this CodatDataContractsValidationValidationItem.  # noqa: E501


        :return: The validator_name of this CodatDataContractsValidationValidationItem.  # noqa: E501
        :rtype: str
        """
        return self._validator_name

    @validator_name.setter
    def validator_name(self, validator_name):
        """Sets the validator_name of this CodatDataContractsValidationValidationItem.


        :param validator_name: The validator_name of this CodatDataContractsValidationValidationItem.  # noqa: E501
        :type: str
        """

        self._validator_name = validator_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CodatDataContractsValidationValidationItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CodatDataContractsValidationValidationItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
