# coding: utf-8

"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CodatDataContractsPushPushOption(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'CodatDataContractsPushOptionType',
        'display_name': 'str',
        'description': 'str',
        'properties': 'dict(str, CodatDataContractsPushPushOption)',
        'options': 'list[CodatDataContractsPushPushOptionChoice]',
        'required': 'bool',
        'validation': 'CodatDataContractsPushPushValidationInfo',
        'rel': 'str'
    }

    attribute_map = {
        'type': 'type',
        'display_name': 'displayName',
        'description': 'description',
        'properties': 'properties',
        'options': 'options',
        'required': 'required',
        'validation': 'validation',
        'rel': 'rel'
    }

    def __init__(self, type=None, display_name=None, description=None, properties=None, options=None, required=None, validation=None, rel=None):  # noqa: E501
        """CodatDataContractsPushPushOption - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._display_name = None
        self._description = None
        self._properties = None
        self._options = None
        self._required = None
        self._validation = None
        self._rel = None
        self.discriminator = None
        self.type = type
        self.display_name = display_name
        self.description = description
        if properties is not None:
            self.properties = properties
        if options is not None:
            self.options = options
        self.required = required
        if validation is not None:
            self.validation = validation
        if rel is not None:
            self.rel = rel

    @property
    def type(self):
        """Gets the type of this CodatDataContractsPushPushOption.  # noqa: E501


        :return: The type of this CodatDataContractsPushPushOption.  # noqa: E501
        :rtype: CodatDataContractsPushOptionType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this CodatDataContractsPushPushOption.


        :param type: The type of this CodatDataContractsPushPushOption.  # noqa: E501
        :type: CodatDataContractsPushOptionType
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def display_name(self):
        """Gets the display_name of this CodatDataContractsPushPushOption.  # noqa: E501


        :return: The display_name of this CodatDataContractsPushPushOption.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this CodatDataContractsPushPushOption.


        :param display_name: The display_name of this CodatDataContractsPushPushOption.  # noqa: E501
        :type: str
        """
        if display_name is None:
            raise ValueError("Invalid value for `display_name`, must not be `None`")  # noqa: E501

        self._display_name = display_name

    @property
    def description(self):
        """Gets the description of this CodatDataContractsPushPushOption.  # noqa: E501


        :return: The description of this CodatDataContractsPushPushOption.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CodatDataContractsPushPushOption.


        :param description: The description of this CodatDataContractsPushPushOption.  # noqa: E501
        :type: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def properties(self):
        """Gets the properties of this CodatDataContractsPushPushOption.  # noqa: E501


        :return: The properties of this CodatDataContractsPushPushOption.  # noqa: E501
        :rtype: dict(str, CodatDataContractsPushPushOption)
        """
        return self._properties

    @properties.setter
    def properties(self, properties):
        """Sets the properties of this CodatDataContractsPushPushOption.


        :param properties: The properties of this CodatDataContractsPushPushOption.  # noqa: E501
        :type: dict(str, CodatDataContractsPushPushOption)
        """

        self._properties = properties

    @property
    def options(self):
        """Gets the options of this CodatDataContractsPushPushOption.  # noqa: E501


        :return: The options of this CodatDataContractsPushPushOption.  # noqa: E501
        :rtype: list[CodatDataContractsPushPushOptionChoice]
        """
        return self._options

    @options.setter
    def options(self, options):
        """Sets the options of this CodatDataContractsPushPushOption.


        :param options: The options of this CodatDataContractsPushPushOption.  # noqa: E501
        :type: list[CodatDataContractsPushPushOptionChoice]
        """

        self._options = options

    @property
    def required(self):
        """Gets the required of this CodatDataContractsPushPushOption.  # noqa: E501


        :return: The required of this CodatDataContractsPushPushOption.  # noqa: E501
        :rtype: bool
        """
        return self._required

    @required.setter
    def required(self, required):
        """Sets the required of this CodatDataContractsPushPushOption.


        :param required: The required of this CodatDataContractsPushPushOption.  # noqa: E501
        :type: bool
        """
        if required is None:
            raise ValueError("Invalid value for `required`, must not be `None`")  # noqa: E501

        self._required = required

    @property
    def validation(self):
        """Gets the validation of this CodatDataContractsPushPushOption.  # noqa: E501


        :return: The validation of this CodatDataContractsPushPushOption.  # noqa: E501
        :rtype: CodatDataContractsPushPushValidationInfo
        """
        return self._validation

    @validation.setter
    def validation(self, validation):
        """Sets the validation of this CodatDataContractsPushPushOption.


        :param validation: The validation of this CodatDataContractsPushPushOption.  # noqa: E501
        :type: CodatDataContractsPushPushValidationInfo
        """

        self._validation = validation

    @property
    def rel(self):
        """Gets the rel of this CodatDataContractsPushPushOption.  # noqa: E501


        :return: The rel of this CodatDataContractsPushPushOption.  # noqa: E501
        :rtype: str
        """
        return self._rel

    @rel.setter
    def rel(self, rel):
        """Sets the rel of this CodatDataContractsPushPushOption.


        :param rel: The rel of this CodatDataContractsPushPushOption.  # noqa: E501
        :type: str
        """

        self._rel = rel

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CodatDataContractsPushPushOption, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CodatDataContractsPushPushOption):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
