# coding: utf-8

"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CodatPublicApiModelsMetadataAccountCategoriesModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'account_ref': 'CodatPublicApiModelsMetadataAccountRefModel',
        'suggested': 'CodatPublicApiModelsMetadataSuggestedAccountCategoryModel',
        'confirmed': 'CodatPublicApiModelsMetadataConfirmedAccountCategoryModel'
    }

    attribute_map = {
        'account_ref': 'accountRef',
        'suggested': 'suggested',
        'confirmed': 'confirmed'
    }

    def __init__(self, account_ref=None, suggested=None, confirmed=None):  # noqa: E501
        """CodatPublicApiModelsMetadataAccountCategoriesModel - a model defined in Swagger"""  # noqa: E501
        self._account_ref = None
        self._suggested = None
        self._confirmed = None
        self.discriminator = None
        if account_ref is not None:
            self.account_ref = account_ref
        if suggested is not None:
            self.suggested = suggested
        if confirmed is not None:
            self.confirmed = confirmed

    @property
    def account_ref(self):
        """Gets the account_ref of this CodatPublicApiModelsMetadataAccountCategoriesModel.  # noqa: E501


        :return: The account_ref of this CodatPublicApiModelsMetadataAccountCategoriesModel.  # noqa: E501
        :rtype: CodatPublicApiModelsMetadataAccountRefModel
        """
        return self._account_ref

    @account_ref.setter
    def account_ref(self, account_ref):
        """Sets the account_ref of this CodatPublicApiModelsMetadataAccountCategoriesModel.


        :param account_ref: The account_ref of this CodatPublicApiModelsMetadataAccountCategoriesModel.  # noqa: E501
        :type: CodatPublicApiModelsMetadataAccountRefModel
        """

        self._account_ref = account_ref

    @property
    def suggested(self):
        """Gets the suggested of this CodatPublicApiModelsMetadataAccountCategoriesModel.  # noqa: E501


        :return: The suggested of this CodatPublicApiModelsMetadataAccountCategoriesModel.  # noqa: E501
        :rtype: CodatPublicApiModelsMetadataSuggestedAccountCategoryModel
        """
        return self._suggested

    @suggested.setter
    def suggested(self, suggested):
        """Sets the suggested of this CodatPublicApiModelsMetadataAccountCategoriesModel.


        :param suggested: The suggested of this CodatPublicApiModelsMetadataAccountCategoriesModel.  # noqa: E501
        :type: CodatPublicApiModelsMetadataSuggestedAccountCategoryModel
        """

        self._suggested = suggested

    @property
    def confirmed(self):
        """Gets the confirmed of this CodatPublicApiModelsMetadataAccountCategoriesModel.  # noqa: E501


        :return: The confirmed of this CodatPublicApiModelsMetadataAccountCategoriesModel.  # noqa: E501
        :rtype: CodatPublicApiModelsMetadataConfirmedAccountCategoryModel
        """
        return self._confirmed

    @confirmed.setter
    def confirmed(self, confirmed):
        """Sets the confirmed of this CodatPublicApiModelsMetadataAccountCategoriesModel.


        :param confirmed: The confirmed of this CodatPublicApiModelsMetadataAccountCategoriesModel.  # noqa: E501
        :type: CodatPublicApiModelsMetadataConfirmedAccountCategoryModel
        """

        self._confirmed = confirmed

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CodatPublicApiModelsMetadataAccountCategoriesModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CodatPublicApiModelsMetadataAccountCategoriesModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
