# coding: utf-8

"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CodatDataContractsPushPushFieldValidation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'field': 'str',
        'details': 'str',
        'ref': 'str'
    }

    attribute_map = {
        'field': 'field',
        'details': 'details',
        'ref': 'ref'
    }

    def __init__(self, field=None, details=None, ref=None):  # noqa: E501
        """CodatDataContractsPushPushFieldValidation - a model defined in Swagger"""  # noqa: E501
        self._field = None
        self._details = None
        self._ref = None
        self.discriminator = None
        self.field = field
        self.details = details
        if ref is not None:
            self.ref = ref

    @property
    def field(self):
        """Gets the field of this CodatDataContractsPushPushFieldValidation.  # noqa: E501


        :return: The field of this CodatDataContractsPushPushFieldValidation.  # noqa: E501
        :rtype: str
        """
        return self._field

    @field.setter
    def field(self, field):
        """Sets the field of this CodatDataContractsPushPushFieldValidation.


        :param field: The field of this CodatDataContractsPushPushFieldValidation.  # noqa: E501
        :type: str
        """
        if field is None:
            raise ValueError("Invalid value for `field`, must not be `None`")  # noqa: E501

        self._field = field

    @property
    def details(self):
        """Gets the details of this CodatDataContractsPushPushFieldValidation.  # noqa: E501


        :return: The details of this CodatDataContractsPushPushFieldValidation.  # noqa: E501
        :rtype: str
        """
        return self._details

    @details.setter
    def details(self, details):
        """Sets the details of this CodatDataContractsPushPushFieldValidation.


        :param details: The details of this CodatDataContractsPushPushFieldValidation.  # noqa: E501
        :type: str
        """
        if details is None:
            raise ValueError("Invalid value for `details`, must not be `None`")  # noqa: E501

        self._details = details

    @property
    def ref(self):
        """Gets the ref of this CodatDataContractsPushPushFieldValidation.  # noqa: E501


        :return: The ref of this CodatDataContractsPushPushFieldValidation.  # noqa: E501
        :rtype: str
        """
        return self._ref

    @ref.setter
    def ref(self, ref):
        """Sets the ref of this CodatDataContractsPushPushFieldValidation.


        :param ref: The ref of this CodatDataContractsPushPushFieldValidation.  # noqa: E501
        :type: str
        """

        self._ref = ref

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CodatDataContractsPushPushFieldValidation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CodatDataContractsPushPushFieldValidation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
