# flake8: noqa

"""
    Codat API

    [What's changed in our Swagger](https://docs.codat.io/docs/new-swagger-ui)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from codat_python_sdk.api_client import ApiClient

# import Configuration
from codat_python_sdk.configuration import Configuration

# import exceptions
from codat_python_sdk.exceptions import OpenApiException
from codat_python_sdk.exceptions import ApiAttributeError
from codat_python_sdk.exceptions import ApiTypeError
from codat_python_sdk.exceptions import ApiValueError
from codat_python_sdk.exceptions import ApiKeyError
from codat_python_sdk.exceptions import ApiException
